/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed-variant': '#104e52',
        'primary-container': '#00464a',
        'inverse-on-surface': '#f2f0ed',
        'outline': '#707979',
        'surface-container-high': '#eae8e5',
        'secondary': '#4c6453',
        'surface-container': '#efeeeb',
        'error-container': '#ffdad6',
        'on-tertiary-fixed-variant': '#5d4201',
        'surface-variant': '#e4e2df',
        'on-tertiary-container': '#caa45d',
        'on-background': '#1b1c1a',
        'primary': '#002e31',
        'error': '#ba1a1a',
        'inverse-surface': '#30312f',
        'on-secondary-fixed-variant': '#354c3c',
        'on-secondary': '#ffffff',
        'secondary-container': '#cce6d1',
        'surface': '#fbf9f6',
        'on-primary': '#ffffff',
        'on-primary-container': '#7cb3b7',
        'tertiary-container': '#533a00',
        'on-secondary-fixed': '#0a2013',
        'on-tertiary': '#ffffff',
        'surface-bright': '#fbf9f6',
        'on-tertiary-fixed': '#261900',
        'on-secondary-container': '#516857',
        'on-error-container': '#93000a',
        'inverse-primary': '#98d0d4',
        'secondary-fixed-dim': '#b3cdb9',
        'surface-container-lowest': '#ffffff',
        'tertiary': '#372600',
        'background': '#fbf9f6',
        'surface-container-highest': '#e4e2df',
        'outline-variant': '#bfc8c9',
        'on-primary-fixed': '#002022',
        'tertiary-fixed-dim': '#e9c176',
        'primary-fixed': '#b4ecf1',
        'tertiary-fixed': '#ffdea5',
        'on-surface': '#1b1c1a',
        'on-surface-variant': '#404849',
        'surface-tint': '#2e676b',
        'surface-dim': '#dbdad7',
        'secondary-fixed': '#cfe9d4',
        'on-error': '#ffffff',
        'primary-fixed-dim': '#98d0d4',
        'surface-container-low': '#f5f3f0',
      },
      fontFamily: {
        'display-md': ['Noto Serif', 'serif'],
        'headline-lg': ['Noto Serif', 'serif'],
        'headline-md': ['Noto Serif', 'serif'],
        'display-lg': ['Noto Serif', 'serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        'body-md': ['Manrope', 'sans-serif'],
        'label-caps': ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
